dist: xenial

language: python

python:
- '3.5'
- '3.6'
- '3.7'

os:
    - linux
    - osx

install:
- pip install zstandard docutils pygments Cython
- pip install https://github.com/cta-observatory/pyhessio/archive/v2.1.1.tar.gz
- pip install .

before_script:
- pip install --upgrade pytest>=3.0.0

script:
- python setup.py test
- python setup.py check -r -s

deploy:
  - provider: pypi
    distributions: sdist
    skip_existing: true
    skip_cleanup: true
    user: cta-observatory
    password:
      secure: Ne3Rf08D32yP5+w96yRk/YwVIwCQLvtld7cxRxoD4mtzs5Xmc9PTIG+dVGOMzEM9auMptg0xCg/Zcs11JA/k8yLWWhqhXGi0tJ2+cA41tK0T8/It5YszW3n9zjc2hrxDClh660BGkR90nCcbWaQRrcfz9ARGJD8f11STu+7Jpr/GjLZurJPwKPmKfcHzwp8Juxp/pcUuGj8/lC/PSOXXota9fKSV0ZZfRshnyhlQmySmcVoOow0whUp7rQt5pZODd2IaNsoxIK2hG70+K5TK1VbCJuJ9bEgWGmW1WgAS7FebKYg4tcFjIDJ4RCfEgzj/0pydYdTWhwnYnkO7xT6RHtRhx4f2m2EaBKd9VMC6olzICacpXRKyFY0FX/JRj6ZrOYM/QOcZnRCY3ikuVkYo/E8RQX+hddc8IM5b7vX8jIIyS6XXT3zI7eJuP0AvGgmNjvuuv87RCd53HS6V8WuMC9gG28nlxJomIENG748gWYUBp4Jge0TbyF7iJkEo0eH27xO8Pu1PEI6iLGA9/YXdBsirfP1hZVbrXhtItQ7UUEi13cowWNsmMeGAP0EreRIH5R74y1UXnbvpKeRapXl4C/Ka7Gce95Ajytd+tFdxk2QqIpOeXu5m/L2COgaIjXu9exq0CjKnUjMpVrECVgCT4lEfa0OPTdMLcBVoBohlfA4=
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "3.7"
