# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.9.2.dev4+gbdee041.d20220907'
__version_tuple__ = version_tuple = (1, 9, 2, 'dev4', 'gbdee041.d20220907')
