name: Deploy

on:
  push:
    tags:
      - 'v*'
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist/
        env:
          # only build cpython
          CIBW_BUILD: "cp*"
          # exclude 32 bit and musl architectures to reduce build time
          # these shouldn't be needed
          CIBW_SKIP: "*-win32 *-manylinux_i686 *musllinux*"

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.whl
          name: dist-wheels-${{ matrix.os }}-${{ strategy.job-index }}

  build_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build sdist
        run: |
          python --version
          pip install -U build
          python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.tar.gz
          name: dist-sdist

  pypi_upload:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs:
      - build_wheels
      - build_sdist
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          # unpacks all dist artifacts into dist/
          pattern: dist-*
          path: dist
          merge-multiple: true


      - name: Check files
        run: ls -l dist

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1

        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
